export type PsxSymbolMetadata = {
  symbol: string;
  sector?: string;
  updatedAt?: string;
};

export const PSX_SYMBOL_METADATA: Record<string, PsxSymbolMetadata> = {
  786: { symbol: "786", sector: "INV BANKS" },
  AABS: { symbol: "AABS", sector: "SUGAR" },
  AATM: { symbol: "AATM", sector: "TEXTILE SPIN" },
  ABL: { symbol: "ABL", sector: "BANKS" },
  ABOT: { symbol: "ABOT", sector: "PHARMA" },
  ACIETF: { symbol: "ACIETF", sector: "ETFS" },
  ACPL: { symbol: "ACPL", sector: "CEMENT" },
  ADAMS: { symbol: "ADAMS", sector: "SUGAR" },
  ADMM: { symbol: "ADMM", sector: "TEXTILE COMP" },
  AGHA: { symbol: "AGHA", sector: "ENGINEERING" },
  AGIC: { symbol: "AGIC", sector: "INSURANCE" },
  AGIL: { symbol: "AGIL", sector: "AUTO PARTS" },
  AGL: { symbol: "AGL", sector: "CHEMICAL" },
  AGP: { symbol: "AGP", sector: "PHARMA" },
  AGSML: { symbol: "AGSML", sector: "SUGAR" },
  AGTL: { symbol: "AGTL", sector: "AUTO ASSEMBLER" },
  AHCL: { symbol: "AHCL", sector: "FERTILIZER" },
  AHL: { symbol: "AHL", sector: "INV BANKS" },
  AHTM: { symbol: "AHTM", sector: "TEXTILE COMP" },
  AICL: { symbol: "AICL", sector: "INSURANCE" },
  AIRLINK: { symbol: "AIRLINK", sector: "TECH & COMM" },
  AKBL: { symbol: "AKBL", sector: "BANKS" },
  AKDHL: { symbol: "AKDHL", sector: "MISC" },
  AKDSL: { symbol: "AKDSL", sector: "INV BANKS" },
  AKGL: { symbol: "AKGL", sector: "MISC" },
  ALAC: { symbol: "ALAC", sector: "INSURANCE" },
  ALIFE: { symbol: "ALIFE", sector: "INSURANCE" },
  ALNRS: { symbol: "ALNRS", sector: "SUGAR" },
  ALTN: { symbol: "ALTN", sector: "POWER" },
  AMBL: { symbol: "AMBL", sector: "INV BANKS" },
  AMTEX: { symbol: "AMTEX", sector: "TEXTILE SPIN" },
  ANL: { symbol: "ANL", sector: "TEXTILE COMP" },
  ANSM: { symbol: "ANSM", sector: "SUGAR" },
  ANTM: { symbol: "ANTM", sector: "TEXTILE COMP" },
  APL: { symbol: "APL", sector: "O&G MKT" },
  ARCTM: { symbol: "ARCTM", sector: "TEXTILE SPIN" },
  ARPAK: { symbol: "ARPAK", sector: "MISC" },
  ARPL: { symbol: "ARPL", sector: "CHEMICAL" },
  ARUJ: { symbol: "ARUJ", sector: "TEXTILE COMP" },
  ASC: { symbol: "ASC", sector: "FOOD & CARE" },
  ASHT: { symbol: "ASHT", sector: "TEXTILE WEAV" },
  ASIC: { symbol: "ASIC", sector: "INSURANCE" },
  ASL: { symbol: "ASL", sector: "ENGINEERING" },
  ASTL: { symbol: "ASTL", sector: "ENGINEERING" },
  ASTM: { symbol: "ASTM", sector: "TEXTILE SPIN" },
  ATBA: { symbol: "ATBA", sector: "AUTO PARTS" },
  ATIL: { symbol: "ATIL", sector: "INSURANCE" },
  ATLH: { symbol: "ATLH", sector: "AUTO ASSEMBLER" },
  ATRL: { symbol: "ATRL", sector: "REFINERY" },
  AVN: { symbol: "AVN", sector: "TECH & COMM" },
  BAFL: { symbol: "BAFL", sector: "BANKS" },
  BAFS: { symbol: "BAFS", sector: "SUGAR" },
  BAHL: { symbol: "BAHL", sector: "BANKS" },
  BAPL: { symbol: "BAPL", sector: "CHEMICAL" },
  BATA: { symbol: "BATA", sector: "LEATHER" },
  BBFL: { symbol: "BBFL", sector: "FOOD & CARE" },
  BCL: { symbol: "BCL", sector: "ENGINEERING" },
  BECO: { symbol: "BECO", sector: "ENGINEERING" },
  BELA: { symbol: "BELA", sector: "AUTO PARTS" },
  BERG: { symbol: "BERG", sector: "CHEMICAL" },
  BFAGRO: { symbol: "BFAGRO", sector: "FOOD & CARE" },
  BFBIO: { symbol: "BFBIO", sector: "PHARMA" },
  BFMOD: { symbol: "BFMOD", sector: "MODARABAS" },
  BGL: { symbol: "BGL", sector: "GLASS & CERAM" },
  BHAT: { symbol: "BHAT", sector: "TEXTILE COMP" },
  BIFO: { symbol: "BIFO", sector: "CHEMICAL" },
  BIPL: { symbol: "BIPL", sector: "BANKS" },
  BML: { symbol: "BML", sector: "BANKS" },
  BNL: { symbol: "BNL", sector: "FOOD & CARE" },
  BNWM: { symbol: "BNWM", sector: "WOOLLEN" },
  BOK: { symbol: "BOK", sector: "BANKS" },
  BOP: { symbol: "BOP", sector: "BANKS" },
  BPL: { symbol: "BPL", sector: "O&G MKT" },
  BRRG: { symbol: "BRRG", sector: "PROPERTY" },
  BTL: { symbol: "BTL", sector: "TEXTILE COMP" },
  BUXL: { symbol: "BUXL", sector: "CHEMICAL" },
  BWCL: { symbol: "BWCL", sector: "CEMENT" },
  BWHL: { symbol: "BWHL", sector: "AUTO PARTS" },
  CCM: { symbol: "CCM", sector: "TEXTILE SPIN" },
  CENI: { symbol: "CENI", sector: "INSURANCE" },
  CEPB: { symbol: "CEPB", sector: "PAPER & PACK" },
  CFL: { symbol: "CFL", sector: "TEXTILE SPIN" },
  CHAS: { symbol: "CHAS", sector: "SUGAR" },
  CHBL: { symbol: "CHBL", sector: "TEXTILE COMP" },
  CHCC: { symbol: "CHCC", sector: "CEMENT" },
  CJPL: { symbol: "CJPL", sector: "JUTE" },
  CLOV: { symbol: "CLOV", sector: "FOOD & CARE" },
  CLVL: { symbol: "CLVL", sector: "TRANSPORT" },
  CNERGY: { symbol: "CNERGY", sector: "REFINERY" },
  COLG: { symbol: "COLG", sector: "FOOD & CARE" },
  CPHL: { symbol: "CPHL", sector: "PHARMA" },
  CPPL: { symbol: "CPPL", sector: "PAPER & PACK" },
  CRTM: { symbol: "CRTM", sector: "TEXTILE COMP" },
  CSAP: { symbol: "CSAP", sector: "ENGINEERING" },
  CSIL: { symbol: "CSIL", sector: "INSURANCE" },
  CTM: { symbol: "CTM", sector: "TEXTILE SPIN" },
  DAAG: { symbol: "DAAG", sector: "CHEMICAL" },
  DADX: { symbol: "DADX", sector: "ENGINEERING" },
  DBCI: { symbol: "DBCI", sector: "CEMENT" },
  DCL: { symbol: "DCL", sector: "CEMENT" },
  DCR: { symbol: "DCR", sector: "REAL ESTATE" },
  DEL: { symbol: "DEL", sector: "INV BANKS" },
  DFML: { symbol: "DFML", sector: "AUTO ASSEMBLER" },
  DFSM: { symbol: "DFSM", sector: "TEXTILE SPIN" },
  DGKC: { symbol: "DGKC", sector: "CEMENT" },
  DIIL: { symbol: "DIIL", sector: "MISC" },
  DINT: { symbol: "DINT", sector: "TEXTILE SPIN" },
  DLL: { symbol: "DLL", sector: "INV BANKS" },
  DNCC: { symbol: "DNCC", sector: "CEMENT" },
  DOL: { symbol: "DOL", sector: "CHEMICAL" },
  DSIL: { symbol: "DSIL", sector: "TEXTILE SPIN" },
  DSL: { symbol: "DSL", sector: "ENGINEERING" },
  DWAE: { symbol: "DWAE", sector: "AUTO PARTS" },
  DWSM: { symbol: "DWSM", sector: "SUGAR" },
  DWTM: { symbol: "DWTM", sector: "TEXTILE SPIN" },
  DYNO: { symbol: "DYNO", sector: "CHEMICAL" },
  ECOP: { symbol: "ECOP", sector: "MISC" },
  EFERT: { symbol: "EFERT", sector: "FERTILIZER" },
  EFUG: { symbol: "EFUG", sector: "INSURANCE" },
  EFUL: { symbol: "EFUL", sector: "INSURANCE" },
  ELCM: { symbol: "ELCM", sector: "TEXTILE SPIN" },
  ELSM: { symbol: "ELSM", sector: "TEXTILE SPIN" },
  EMCO: { symbol: "EMCO", sector: "CABLE & ELEC" },
  ENGROH: { symbol: "ENGROH", sector: "INV BANKS" },
  EPCL: { symbol: "EPCL", sector: "CHEMICAL" },
  EPQL: { symbol: "EPQL", sector: "POWER" },
  ESBL: { symbol: "ESBL", sector: "INV BANKS" },
  EWIC: { symbol: "EWIC", sector: "INSURANCE" },
  EXIDE: { symbol: "EXIDE", sector: "AUTO PARTS" },
  FABL: { symbol: "FABL", sector: "BANKS" },
  FANM: { symbol: "FANM", sector: "MODARABAS" },
  FASM: { symbol: "FASM", sector: "TEXTILE COMP" },
  FATIMA: { symbol: "FATIMA", sector: "FERTILIZER" },
  FCCL: { symbol: "FCCL", sector: "CEMENT" },
  FCEL: { symbol: "FCEL", sector: "INV BANKS" },
  FCEPL: { symbol: "FCEPL", sector: "FOOD & CARE" },
  FCIBL: { symbol: "FCIBL", sector: "INV BANKS" },
  FCL: { symbol: "FCL", sector: "CABLE & ELEC" },
  FCSC: { symbol: "FCSC", sector: "INV BANKS" },
  FDPL: { symbol: "FDPL", sector: "INV BANKS" },
  FECM: { symbol: "FECM", sector: "MODARABAS" },
  FECTC: { symbol: "FECTC", sector: "CEMENT" },
  FEM: { symbol: "FEM", sector: "MODARABAS" },
  FEROZ: { symbol: "FEROZ", sector: "PHARMA" },
  FFC: { symbol: "FFC", sector: "FERTILIZER" },
  FFL: { symbol: "FFL", sector: "FOOD & CARE" },
  FFLM: { symbol: "FFLM", sector: "MODARABAS" },
  FHAM: { symbol: "FHAM", sector: "MODARABAS" },
  FIBLM: { symbol: "FIBLM", sector: "MODARABAS" },
  FIL: { symbol: "FIL", sector: "LEATHER" },
  FIMM: { symbol: "FIMM", sector: "MODARABAS" },
  FLYNG: { symbol: "FLYNG", sector: "CEMENT" },
  FML: { symbol: "FML", sector: "TEXTILE COMP" },
  FNEL: { symbol: "FNEL", sector: "INV BANKS" },
  FPJM: { symbol: "FPJM", sector: "MODARABAS" },
  FPRM: { symbol: "FPRM", sector: "MODARABAS" },
  FRCL: { symbol: "FRCL", sector: "GLASS & CERAM" },
  FRSM: { symbol: "FRSM", sector: "SUGAR" },
  FSWL: { symbol: "FSWL", sector: "TEXTILE COMP" },
  FTMM: { symbol: "FTMM", sector: "MODARABAS" },
  FTSM: { symbol: "FTSM", sector: "MODARABAS" },
  FZCM: { symbol: "FZCM", sector: "TEXTILE COMP" },
  GADT: { symbol: "GADT", sector: "TEXTILE SPIN" },
  GAL: { symbol: "GAL", sector: "AUTO ASSEMBLER" },
  GAMON: { symbol: "GAMON", sector: "MISC" },
  GATI: { symbol: "GATI", sector: "SYNTHETIC" },
  GATM: { symbol: "GATM", sector: "TEXTILE COMP" },
  GCIL: { symbol: "GCIL", sector: "CHEMICAL" },
  GEMPAPL: { symbol: "GEMPAPL", sector: "PAPER & PACK" },
  GFIL: { symbol: "GFIL", sector: "TEXTILE COMP" },
  GGGL: { symbol: "GGGL", sector: "GLASS & CERAM" },
  GGL: { symbol: "GGL", sector: "CHEMICAL" },
  GHGL: { symbol: "GHGL", sector: "GLASS & CERAM" },
  GHNI: { symbol: "GHNI", sector: "AUTO ASSEMBLER" },
  GLAXO: { symbol: "GLAXO", sector: "PHARMA" },
  GLPL: { symbol: "GLPL", sector: "FOOD & CARE" },
  GOC: { symbol: "GOC", sector: "MISC" },
  GRR: { symbol: "GRR", sector: "REAL ESTATE" },
  GRYL: { symbol: "GRYL", sector: "LEASING" },
  GSPM: { symbol: "GSPM", sector: "TEXTILE SPIN" },
  GTYR: { symbol: "GTYR", sector: "AUTO PARTS" },
  GUSM: { symbol: "GUSM", sector: "TEXTILE SPIN" },
  GVGL: { symbol: "GVGL", sector: "GLASS & CERAM" },
  GWLC: { symbol: "GWLC", sector: "CEMENT" },
  HABSM: { symbol: "HABSM", sector: "SUGAR" },
  HAEL: { symbol: "HAEL", sector: "TEXTILE COMP" },
  HAFL: { symbol: "HAFL", sector: "TEXTILE COMP" },
  HALEON: { symbol: "HALEON", sector: "PHARMA" },
  HASCOL: { symbol: "HASCOL", sector: "O&G MKT" },
  HBL: { symbol: "HBL", sector: "BANKS" },
  HBLTETF: { symbol: "HBLTETF", sector: "ETFS" },
  HCAR: { symbol: "HCAR", sector: "AUTO ASSEMBLER" },
  HGFA: { symbol: "HGFA", sector: "MUTUAL FUND" },
  HICL: { symbol: "HICL", sector: "INSURANCE" },
  HIFA: { symbol: "HIFA", sector: "MUTUAL FUND" },
  HINO: { symbol: "HINO", sector: "AUTO ASSEMBLER" },
  HINOON: { symbol: "HINOON", sector: "PHARMA" },
  HIRAT: { symbol: "HIRAT", sector: "TEXTILE SPIN" },
  HMB: { symbol: "HMB", sector: "BANKS" },
  HPL: { symbol: "HPL", sector: "PHARMA" },
  HRPL: { symbol: "HRPL", sector: "SUGAR" },
  HTL: { symbol: "HTL", sector: "O&G MKT" },
  HUBC: { symbol: "HUBC", sector: "POWER" },
  HUMNL: { symbol: "HUMNL", sector: "TECH & COMM" },
  HUSI: { symbol: "HUSI", sector: "PROPERTY" },
  HWQS: { symbol: "HWQS", sector: "SUGAR" },
  IBFL: { symbol: "IBFL", sector: "SYNTHETIC" },
  IBLHL: { symbol: "IBLHL", sector: "PHARMA" },
  ICCI: { symbol: "ICCI", sector: "TEXTILE WEAV" },
  ICIBL: { symbol: "ICIBL", sector: "INV BANKS" },
  ICL: { symbol: "ICL", sector: "CHEMICAL" },
  IDRT: { symbol: "IDRT", sector: "TEXTILE SPIN" },
  IDSM: { symbol: "IDSM", sector: "TEXTILE SPIN" },
  IDYM: { symbol: "IDYM", sector: "TEXTILE SPIN" },
  IGIHL: { symbol: "IGIHL", sector: "INSURANCE" },
  IGIL: { symbol: "IGIL", sector: "INSURANCE" },
  ILP: { symbol: "ILP", sector: "TEXTILE COMP" },
  IMAGE: { symbol: "IMAGE", sector: "SYNTHETIC" },
  IML: { symbol: "IML", sector: "INV BANKS" },
  IMS: { symbol: "IMS", sector: "INV BANKS" },
  INDU: { symbol: "INDU", sector: "AUTO ASSEMBLER" },
  INIL: { symbol: "INIL", sector: "ENGINEERING" },
  INKL: { symbol: "INKL", sector: "TEXTILE COMP" },
  IPAK: { symbol: "IPAK", sector: "PAPER & PACK" },
  ISIL: { symbol: "ISIL", sector: "FOOD & CARE" },
  ISL: { symbol: "ISL", sector: "ENGINEERING" },
  ITTEFAQ: { symbol: "ITTEFAQ", sector: "ENGINEERING" },
  JATM: { symbol: "JATM", sector: "TEXTILE SPIN" },
  JDMT: { symbol: "JDMT", sector: "TEXTILE SPIN" },
  JDWS: { symbol: "JDWS", sector: "SUGAR" },
  JGICL: { symbol: "JGICL", sector: "INSURANCE" },
  JKSM: { symbol: "JKSM", sector: "TEXTILE SPIN" },
  JLICL: { symbol: "JLICL", sector: "INSURANCE" },
  JSBL: { symbol: "JSBL", sector: "BANKS" },
  JSCL: { symbol: "JSCL", sector: "INV BANKS" },
  JSGBETF: { symbol: "JSGBETF", sector: "ETFS" },
  JSGCL: { symbol: "JSGCL", sector: "INV BANKS" },
  JSIL: { symbol: "JSIL", sector: "INV BANKS" },
  JSMFETF: { symbol: "JSMFETF", sector: "ETFS" },
  JSML: { symbol: "JSML", sector: "SUGAR" },
  JUBS: { symbol: "JUBS", sector: "TEXTILE COMP" },
  JVDC: { symbol: "JVDC", sector: "PROPERTY" },
  KAPCO: { symbol: "KAPCO", sector: "POWER" },
  KCL: { symbol: "KCL", sector: "GLASS & CERAM" },
  KEL: { symbol: "KEL", sector: "POWER" },
  KHTC: { symbol: "KHTC", sector: "TOBACCO" },
  KHYT: { symbol: "KHYT", sector: "TEXTILE COMP" },
  KML: { symbol: "KML", sector: "TEXTILE COMP" },
  KOHC: { symbol: "KOHC", sector: "CEMENT" },
  KOHE: { symbol: "KOHE", sector: "POWER" },
  KOHP: { symbol: "KOHP", sector: "POWER" },
  KOHTM: { symbol: "KOHTM", sector: "TEXTILE SPIN" },
  KOIL: { symbol: "KOIL", sector: "TEXTILE COMP" },
  KOSM: { symbol: "KOSM", sector: "TEXTILE SPIN" },
  KPUS: { symbol: "KPUS", sector: "SUGAR" },
  KSBP: { symbol: "KSBP", sector: "ENGINEERING" },
  KSTM: { symbol: "KSTM", sector: "TEXTILE SPIN" },
  KTML: { symbol: "KTML", sector: "TEXTILE COMP" },
  LCI: { symbol: "LCI", sector: "CHEMICAL" },
  LEUL: { symbol: "LEUL", sector: "LEATHER" },
  LIVEN: { symbol: "LIVEN", sector: "PHARMA" },
  LOADS: { symbol: "LOADS", sector: "AUTO PARTS" },
  LOTCHEM: { symbol: "LOTCHEM", sector: "CHEMICAL" },
  LPGL: { symbol: "LPGL", sector: "CHEMICAL" },
  LPL: { symbol: "LPL", sector: "POWER" },
  LSECL: { symbol: "LSECL", sector: "INV BANKS" },
  LSEFSL: { symbol: "LSEFSL", sector: "INV BANKS" },
  LSEVL: { symbol: "LSEVL", sector: "INV BANKS" },
  LUCK: { symbol: "LUCK", sector: "CEMENT" },
  MACFL: { symbol: "MACFL", sector: "PAPER & PACK" },
  MACTER: { symbol: "MACTER", sector: "PHARMA" },
  MARI: { symbol: "MARI", sector: "O&G EXPL" },
  MCB: { symbol: "MCB", sector: "BANKS" },
  MCBIM: { symbol: "MCBIM", sector: "INV BANKS" },
  MDTL: { symbol: "MDTL", sector: "TECH & COMM" },
  MEBL: { symbol: "MEBL", sector: "BANKS" },
  MEHT: { symbol: "MEHT", sector: "TEXTILE COMP" },
  MERIT: { symbol: "MERIT", sector: "PAPER & PACK" },
  MFFL: { symbol: "MFFL", sector: "FOOD & CARE" },
  MFL: { symbol: "MFL", sector: "FOOD & CARE" },
  MIIETF: { symbol: "MIIETF", sector: "ETFS" },
  MIRKS: { symbol: "MIRKS", sector: "SUGAR" },
  MLCF: { symbol: "MLCF", sector: "CEMENT" },
  MQTM: { symbol: "MQTM", sector: "TEXTILE SPIN" },
  MRNS: { symbol: "MRNS", sector: "SUGAR" },
  MSCL: { symbol: "MSCL", sector: "ENGINEERING" },
  MSOT: { symbol: "MSOT", sector: "TEXTILE COMP" },
  MTL: { symbol: "MTL", sector: "AUTO ASSEMBLER" },
  MUGHAL: { symbol: "MUGHAL", sector: "ENGINEERING" },
  MUREB: { symbol: "MUREB", sector: "FOOD & CARE" },
  MWMP: { symbol: "MWMP", sector: "MISC" },
  MZNPETF: { symbol: "MZNPETF", sector: "ETFS" },
  NAGC: { symbol: "NAGC", sector: "TEXTILE SPIN" },
  NATF: { symbol: "NATF", sector: "FOOD & CARE" },
  NBP: { symbol: "NBP", sector: "BANKS" },
  NBPGETF: { symbol: "NBPGETF", sector: "ETFS" },
  NCL: { symbol: "NCL", sector: "TEXTILE COMP" },
  NCML: { symbol: "NCML", sector: "TEXTILE SPIN" },
  NCPL: { symbol: "NCPL", sector: "POWER" },
  NESTLE: { symbol: "NESTLE", sector: "FOOD & CARE" },
  NETSOL: { symbol: "NETSOL", sector: "TECH & COMM" },
  NEXT: { symbol: "NEXT", sector: "INV BANKS" },
  NICL: { symbol: "NICL", sector: "CHEMICAL" },
  NITGETF: { symbol: "NITGETF", sector: "ETFS" },
  NML: { symbol: "NML", sector: "TEXTILE COMP" },
  NONS: { symbol: "NONS", sector: "SUGAR" },
  NPL: { symbol: "NPL", sector: "POWER" },
  NRL: { symbol: "NRL", sector: "REFINERY" },
  NRSL: { symbol: "NRSL", sector: "CHEMICAL" },
  NSRM: { symbol: "NSRM", sector: "SYNTHETIC" },
  OBOY: { symbol: "OBOY", sector: "O&G MKT" },
  OCTOPUS: { symbol: "OCTOPUS", sector: "TECH & COMM" },
  OGDC: { symbol: "OGDC", sector: "O&G EXPL" },
  OLPL: { symbol: "OLPL", sector: "INV BANKS" },
  OLPM: { symbol: "OLPM", sector: "MODARABAS" },
  OML: { symbol: "OML", sector: "MISC" },
  ORM: { symbol: "ORM", sector: "MODARABAS" },
  OTSU: { symbol: "OTSU", sector: "PHARMA" },
  PABC: { symbol: "PABC", sector: "MISC" },
  PACE: { symbol: "PACE", sector: "PROPERTY" },
  PAEL: { symbol: "PAEL", sector: "CABLE & ELEC" },
  PAKD: { symbol: "PAKD", sector: "TECH & COMM" },
  PAKL: { symbol: "PAKL", sector: "LEATHER" },
  PAKOXY: { symbol: "PAKOXY", sector: "CHEMICAL" },
  PAKRI: { symbol: "PAKRI", sector: "INSURANCE" },
  PAKT: { symbol: "PAKT", sector: "TOBACCO" },
  PASL: { symbol: "PASL", sector: "INV BANKS" },
  PASM: { symbol: "PASM", sector: "TEXTILE COMP" },
  PCAL: { symbol: "PCAL", sector: "CABLE & ELEC" },
  PECO: { symbol: "PECO", sector: "ENGINEERING" },
  PGLC: { symbol: "PGLC", sector: "LEASING" },
  PIAHCLA: { symbol: "PIAHCLA", sector: "INV BANKS" },
  PIAHCLB: { symbol: "PIAHCLB", sector: "INV BANKS" },
  PIBTL: { symbol: "PIBTL", sector: "TRANSPORT" },
  PICT: { symbol: "PICT", sector: "TRANSPORT" },
  PIL: { symbol: "PIL", sector: "INSURANCE" },
  PIM: { symbol: "PIM", sector: "MODARABAS" },
  PINL: { symbol: "PINL", sector: "INSURANCE" },
  PIOC: { symbol: "PIOC", sector: "CEMENT" },
  PKGI: { symbol: "PKGI", sector: "INSURANCE" },
  PKGP: { symbol: "PKGP", sector: "POWER" },
  PKGS: { symbol: "PKGS", sector: "PAPER & PACK" },
  PMRS: { symbol: "PMRS", sector: "SUGAR" },
  PNSC: { symbol: "PNSC", sector: "TRANSPORT" },
  POL: { symbol: "POL", sector: "O&G EXPL" },
  POML: { symbol: "POML", sector: "VANASPATI" },
  POWER: { symbol: "POWER", sector: "CEMENT" },
  PPL: { symbol: "PPL", sector: "O&G EXPL" },
  PPP: { symbol: "PPP", sector: "PAPER & PACK" },
  PPVC: { symbol: "PPVC", sector: "CHEMICAL" },
  PREMA: { symbol: "PREMA", sector: "FOOD & CARE" },
  PRET: { symbol: "PRET", sector: "TEXTILE SPIN" },
  PRL: { symbol: "PRL", sector: "REFINERY" },
  PRWM: { symbol: "PRWM", sector: "TEXTILE WEAV" },
  PSEL: { symbol: "PSEL", sector: "MISC" },
  PSO: { symbol: "PSO", sector: "O&G MKT" },
  PSX: { symbol: "PSX", sector: "INV BANKS" },
  PSYL: { symbol: "PSYL", sector: "SYNTHETIC" },
  PTC: { symbol: "PTC", sector: "TECH & COMM" },
  PTL: { symbol: "PTL", sector: "AUTO PARTS" },
  QUET: { symbol: "QUET", sector: "TEXTILE COMP" },
  QUICE: { symbol: "QUICE", sector: "FOOD & CARE" },
  REDCO: { symbol: "REDCO", sector: "TEXTILE COMP" },
  REWM: { symbol: "REWM", sector: "TEXTILE COMP" },
  RICL: { symbol: "RICL", sector: "INSURANCE" },
  RMPL: { symbol: "RMPL", sector: "FOOD & CARE" },
  RPL: { symbol: "RPL", sector: "PAPER & PACK" },
  RUBY: { symbol: "RUBY", sector: "TEXTILE SPIN" },
  RUPL: { symbol: "RUPL", sector: "SYNTHETIC" },
  SAIF: { symbol: "SAIF", sector: "TEXTILE SPIN" },
  SANSM: { symbol: "SANSM", sector: "SUGAR" },
  SAPT: { symbol: "SAPT", sector: "TEXTILE COMP" },
  SARC: { symbol: "SARC", sector: "CHEMICAL" },
  SASML: { symbol: "SASML", sector: "SUGAR" },
  SAZEW: { symbol: "SAZEW", sector: "AUTO ASSEMBLER" },
  SBL: { symbol: "SBL", sector: "BANKS" },
  SCBPL: { symbol: "SCBPL", sector: "BANKS" },
  SCL: { symbol: "SCL", sector: "FOOD & CARE" },
  SEARL: { symbol: "SEARL", sector: "PHARMA" },
  SEL: { symbol: "SEL", sector: "POWER" },
  SEPL: { symbol: "SEPL", sector: "PAPER & PACK" },
  SERT: { symbol: "SERT", sector: "TEXTILE SPIN" },
  SFL: { symbol: "SFL", sector: "TEXTILE COMP" },
  SGF: { symbol: "SGF", sector: "LEATHER" },
  SGPL: { symbol: "SGPL", sector: "POWER" },
  SHCM: { symbol: "SHCM", sector: "TEXTILE SPIN" },
  SHDT: { symbol: "SHDT", sector: "TEXTILE SPIN" },
  SHEZ: { symbol: "SHEZ", sector: "FOOD & CARE" },
  SHFA: { symbol: "SHFA", sector: "MISC" },
  SHJS: { symbol: "SHJS", sector: "SUGAR" },
  SHNI: { symbol: "SHNI", sector: "INSURANCE" },
  SHSML: { symbol: "SHSML", sector: "SUGAR" },
  SIBL: { symbol: "SIBL", sector: "INV BANKS" },
  SIEM: { symbol: "SIEM", sector: "CABLE & ELEC" },
  SINDM: { symbol: "SINDM", sector: "MODARABAS" },
  SITC: { symbol: "SITC", sector: "CHEMICAL" },
  SKRS: { symbol: "SKRS", sector: "SUGAR" },
  SLGL: { symbol: "SLGL", sector: "TRANSPORT" },
  SLYT: { symbol: "SLYT", sector: "TEXTILE SPIN" },
  SMCPL: { symbol: "SMCPL", sector: "CEMENT" },
  SML: { symbol: "SML", sector: "SUGAR" },
  SNAI: { symbol: "SNAI", sector: "TEXTILE SPIN" },
  SNBL: { symbol: "SNBL", sector: "BANKS" },
  SNGP: { symbol: "SNGP", sector: "O&G MKT" },
  SPEL: { symbol: "SPEL", sector: "PAPER & PACK" },
  SPL: { symbol: "SPL", sector: "CHEMICAL" },
  SPWL: { symbol: "SPWL", sector: "POWER" },
  SRVI: { symbol: "SRVI", sector: "LEATHER" },
  SSGC: { symbol: "SSGC", sector: "O&G MKT" },
  SSML: { symbol: "SSML", sector: "TEXTILE SPIN" },
  SSOM: { symbol: "SSOM", sector: "VANASPATI" },
  STCL: { symbol: "STCL", sector: "GLASS & CERAM" },
  STJT: { symbol: "STJT", sector: "TEXTILE WEAV" },
  STL: { symbol: "STL", sector: "TECH & COMM" },
  STPL: { symbol: "STPL", sector: "MISC" },
  STYLERS: { symbol: "STYLERS", sector: "TEXTILE COMP" },
  SURC: { symbol: "SURC", sector: "TEXTILE COMP" },
  SUTM: { symbol: "SUTM", sector: "TEXTILE SPIN" },
  SYM: { symbol: "SYM", sector: "TECH & COMM" },
  SYS: { symbol: "SYS", sector: "TECH & COMM" },
  SZTM: { symbol: "SZTM", sector: "TEXTILE SPIN" },
  TATM: { symbol: "TATM", sector: "TEXTILE SPIN" },
  TBL: { symbol: "TBL", sector: "AUTO PARTS" },
  TCORP: { symbol: "TCORP", sector: "SUGAR" },
  TELE: { symbol: "TELE", sector: "TECH & COMM" },
  TGL: { symbol: "TGL", sector: "GLASS & CERAM" },
  THALL: { symbol: "THALL", sector: "AUTO PARTS" },
  THCCL: { symbol: "THCCL", sector: "CEMENT" },
  TICL: { symbol: "TICL", sector: "SUGAR" },
  TOMCL: { symbol: "TOMCL", sector: "FOOD & CARE" },
  TOWL: { symbol: "TOWL", sector: "TEXTILE COMP" },
  TPL: { symbol: "TPL", sector: "TECH & COMM" },
  TPLI: { symbol: "TPLI", sector: "INSURANCE" },
  TPLL: { symbol: "TPLL", sector: "TEXTILE SPIN" },
  TPLP: { symbol: "TPLP", sector: "PROPERTY" },
  TPLRF1: { symbol: "TPLRF1", sector: "REAL ESTATE" },
  TPLT: { symbol: "TPLT", sector: "TECH & COMM" },
  TREET: { symbol: "TREET", sector: "FOOD & CARE" },
  TRG: { symbol: "TRG", sector: "TECH & COMM" },
  TRIPF: { symbol: "TRIPF", sector: "MISC" },
  TRSM: { symbol: "TRSM", sector: "MODARABAS" },
  TSBL: { symbol: "TSBL", sector: "INV BANKS" },
  TSMF: { symbol: "TSMF", sector: "MUTUAL FUND" },
  TSML: { symbol: "TSML", sector: "SUGAR" },
  TSPL: { symbol: "TSPL", sector: "POWER" },
  UBDL: { symbol: "UBDL", sector: "MISC" },
  UBL: { symbol: "UBL", sector: "BANKS" },
  UBLPETF: { symbol: "UBLPETF", sector: "ETFS" },
  UCAPM: { symbol: "UCAPM", sector: "MODARABAS" },
  UDLI: { symbol: "UDLI", sector: "MISC" },
  UDPL: { symbol: "UDPL", sector: "MISC" },
  UNIC: { symbol: "UNIC", sector: "INSURANCE" },
  UNITY: { symbol: "UNITY", sector: "FOOD & CARE" },
  UPFL: { symbol: "UPFL", sector: "FOOD & CARE" },
  UVIC: { symbol: "UVIC", sector: "INSURANCE" },
  WAFI: { symbol: "WAFI", sector: "O&G MKT" },
  WAHN: { symbol: "WAHN", sector: "CHEMICAL" },
  WAVES: { symbol: "WAVES", sector: "CABLE & ELEC" },
  WAVESAPP: { symbol: "WAVESAPP", sector: "CABLE & ELEC" },
  WTL: { symbol: "WTL", sector: "TECH & COMM" },
  YOUW: { symbol: "YOUW", sector: "TEXTILE WEAV" },
  ZAHID: { symbol: "ZAHID", sector: "TEXTILE COMP" },
  ZAL: { symbol: "ZAL", sector: "TECH & COMM" },
  ZIL: { symbol: "ZIL", sector: "FOOD & CARE" },
  ZTL: { symbol: "ZTL", sector: "TEXTILE WEAV" },
};

export const PSX_METADATA_UPDATED_AT = "2026-04-25T05:29:31.923Z";

export function getPsxSymbolMetadata(ticker: string) {
  if (!ticker) return undefined;
  return PSX_SYMBOL_METADATA[ticker.toUpperCase()];
}

export function getRealSectorForTicker(ticker: string) {
  const meta = getPsxSymbolMetadata(ticker);
  return meta?.sector ?? null;
}

export function getDisplaySectorForTicker(ticker: string, fallback?: string) {
  const real = getRealSectorForTicker(ticker);

  // prefer real sector from metadata
  if (real && typeof real === "string" && real.trim().length > 0) {
    return real;
  }

  // do NOT treat fallback (mock/replay sector) as authoritative
  return "Unclassified";
}
