begin;

create table if not exists public.analytics_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users (id) on delete set null,
  event_name text not null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists analytics_events_event_name_idx
  on public.analytics_events (event_name);

create index if not exists analytics_events_created_at_idx
  on public.analytics_events (created_at desc);

create index if not exists analytics_events_user_id_idx
  on public.analytics_events (user_id);

alter table public.analytics_events enable row level security;

drop policy if exists "analytics_events_insert_client" on public.analytics_events;
create policy "analytics_events_insert_client"
  on public.analytics_events for insert
  to anon, authenticated
  with check (
    (auth.uid() is null and user_id is null)
    or auth.uid() = user_id
  );

drop policy if exists "analytics_events_select_own" on public.analytics_events;
create policy "analytics_events_select_own"
  on public.analytics_events for select
  to authenticated
  using (auth.uid() = user_id);

grant insert on table public.analytics_events to anon, authenticated;
grant select on table public.analytics_events to authenticated;

commit;
